apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: events-api-data
  namespace: events-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-fast-retain
  resources:
    requests:
      storage: 1Gi
